### ISSUE TITLE
PHP 7.4 Comatibility

### ISSUE THREAD

**Issue by jpswade** [php/pecl-networking-ssh2#61]
```
% pecl install ssh2
pecl/ssh2 requires PHP (version >= 4.0.0, version <= 6.0.0), installed version is 7.4.20
No valid packages found
install failed
```

**Comment by ryandesign** [comment]
It already supports php 7 since version 1.0. Dunno why you're getting that error.

https://pecl.php.net/package-changelog.php?package=ssh2

**Comment by langemeijer** [comment]
`pecl install ssh2-beta`

Will do the trick.
