### ISSUE TITLE
ssh2 php8.2 for windows (.dll file)

### ISSUE THREAD

**Issue by donny26utama** [php/pecl-networking-ssh2#64]
on pecl site, I cant find ssh2 source for php8.2
when this will be available?

**Comment by langemeijer** [comment]
PECL Windows DLL's are built by the windows team. See https://windows.php.net/

Unfortunately there is an infrastructure problem. Because of that, there currently is no dll for PHP 8.2.

Also see: https://externals.io/message/117494

**Comment by cmb69** [comment]
For the record, the DLLs are available again for a couple of months.
