### ISSUE TITLE
Version 1.4 missing on PECL

### ISSUE THREAD

**Issue by remicollet** [php/pecl-networking-ssh2#65]
I notice 1.4 was created a few days ago in a90d5e9759a5f2e2cbbbd9170497edfc9ce04ca9

But

- there is no tag
- there is no pecl release on https://pecl.php.net/package/ssh2 (only 1.3.1)

Can you please clarify ?

**Comment by langemeijer** [comment]
Yes, I packaged but didn't get the tgz through the pecl upload process. I get a perfectly, working "Please verify that the following release information is correct" page. I click the 'Verify Release'  button and get an error:

 "Error while uploading package: Parsing the packagexml for release 9514 failed with error message: XML Error: 'Not well-formed (invalid token)' on line '1'". 

I think I might have uploaded a broken tgz first, then tried again with a repackaged 1.4.

It seems that upload package code on the pecl website is somewhat broken, and although a newer file is uploaded it still keeps trying the old one for some time. I re-uploaded the previously created 1.4 just now and it seems to have worked.

Now the https://pecl.php.net/package/ssh2 page shows some weird stuff for version 1.1.1. This could well be related to this as it seems to match the number of times I tried. (Including changing version number to 1.4.0)

Concerning the git tag, this wasn't in my documentation. I see I missed it in 1.3 too. I will add the tags later.

**Comment by andypost** [comment]
Checked and current 1.4 is packaged fine, thank you!

**Comment by remicollet** [comment]
@langemeijer thanks to @derickr the pecl content have been fixed.
Evertything seems OK now
